{% set name = "esi-utils-rupture" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d3057c29353968a7ee90cce36f682916d4faa5f6302c9d19a90058a304321ea3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm >=3.4
    - pip
  run:
    - numba
    - python >=3.8
    - decorator >=5.1
    - defusedxml >=0.7.1
    - esi-extern-openquake >=1.0.0
    - esi-utils-time >=1.0.0
    - esi-utils-vectors >=1.0.0
    - h5py >=3.7
    - numpy >=1.21,<2.0.0
    - obspy >=1.3.0
    - openquake.engine >=3.14
    - pandas >=1.0
    - ps2ff >=1.5.2
    - psutil >=5.9
    - pyproj >=2.6.1
    - requests >2.28
    - toml >=0.10
    - pyzmq

test:
  imports:
    - esi_utils_rupture
  # pip check cannot recognize beautifulsoup4 is bs4 :-/ in esi_utils_time
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://code.usgs.gov/ghsc/esi/esi-utils-rupture
  summary: USGS Earthquake Impact Utilities for Ruptures
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
