{% set python_min = "3.11" %}
{% set name = "esi-utils-rupture" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c91818132574c83740c265c6cfb1e325f4e75f678a3973ebbd15434826e3e2c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=3.4
    - pip
  run:
    - numba
    - python >={{ python_min }}
    - decorator >=5.1
    - defusedxml >=0.7.1
    - esi-extern-openquake >=1.0.0
    - esi-utils-time >=1.0.0
    - esi-utils-vectors >=1.0.0
    - h5py >=3.7
    - numpy >=1.26
    - obspy >=1.3.0
    - openquake.engine >=3.23
    - numba
    - pandas >=1.0
    - psutil >=5.9
    - pyproj >=2.6.1
    - requests >2.28
    - toml >=0.10

test:
  requires:
    - python {{ python_min }}
  imports:
    - esi_utils_rupture
  # pip check cannot recognize beautifulsoup4 is bs4 :-/ in esi_utils_time
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://code.usgs.gov/ghsc/esi/esi-utils-rupture
  summary: USGS Earthquake Impact Utilities for Ruptures
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
